name = "fast-roll"
main = "worker.js"
compatibility_date = "2024-11-01"

[vars]
PUBLIC_URL = "https://YOUR-R2-PUBLIC-DOMAIN"

[[d1_databases]]
binding = "DB"
database_name = "fastroll"
database_id = "YOUR-D1-ID"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "fastroll"

